import Head from 'next/head';

import Header from '../components/Header';
import Intro from '../components/Intro';

import ImageUpload from '../components/ImageUpload';

import { Pane, } from 'evergreen-ui';

export default function Home() {
    return (
        <Pane width='100vw' height='100vh'>
            <Head>
                    <title>Photong</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <Pane width='100%' display='flex' flexDirection='column' alignItems='center'>
                <Pane display='flex' flexDirection='column' alignItems='center' marginTop={48} marginX={32}>
                    <Intro />
                    <ImageUpload marginTop={32}/>
                </Pane>
            </Pane>
        </Pane>
    )
}
